### ISSUE TITLE
Crash on Dispose

### ISSUE THREAD

**Issue by diegobarile** [Code-Artist/AGauge#1]
Inside the Dispose method the following line could crash:

**this.gaugeBitmap.Dispose();**

This could happens if the control is instantiated but never shown. The gaugeBitmap is instantiated only inside the OnPaint method.

**Comment by Code-Artist** [comment]
Thanks for reporting this issue. What is your suggested fix?

**Comment by diegobarile** [comment]
Hi. I suggest:

protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                **if (null != gaugeBitmap)**
                       gaugeBitmap.Dispose();
                components.Dispose();
            }
            base.Dispose(disposing);
        }

**Comment by Code-Artist** [comment]
Hello Mr. Diego,

You are welcome to push your suggested fixes to this project.
Since this is an open source project, we welcome fixes and improvement from developers to further improve this project. Thank you.

**Comment by Code-Artist** [comment]
Closed. Thanks Mr. Diego for the fixes.

**Comment by diegobarile** [comment]
Is the NuGet package named "AGauge" under your control?
If yes, is it possible release a new version?

Thanks in advance.

**Comment by Code-Artist** [comment]
Nope, I'm not the owner who release the package in NuGet package and I only knew that exist after you told me. Anyway, I will drop the a note to the owner regarding our recent changes.

**Comment by diegobarile** [comment]
That sounds good.
Please remember to increase the version number.

Regards.

**Comment by Code-Artist** [comment]
Unfortunately, I can't control this and the guy who release the package to nuget did not response so far.
