### ISSUE TITLE
Needle properties do not show on other boxes

### ISSUE THREAD

**Issue by Doug4410** [Code-Artist/AGauge#7]
I have set the needle type to advance, but it shows as simple on other boxes.  Is this a known problem?

**Comment by Code-Artist** [comment]
Are you using multiple AGauge components? Have you tried to set needle type to advance for each of the object?

**Comment by Doug4410** [comment]
Thanks for the reply,
I'm only using one AGauge component on a very simple form.  I've tried Setting the needle to advance in the properties and explicitly in the code.

**Comment by Code-Artist** [comment]
Sorry for late reply, please check AGaugeDemo app which having only one Advance gauge included.
You should see Advance needle from this demo project.
